export const FETCH_HOLDINGS = 'FETCH_HOLDINGS';
export const UPDATE_HOLDING = 'UPDATE_HOLDING';
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = 'LOGOUT';
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
